# Site settings
title: Nicolas Arias Garcia
subtitle: Anthropology | Systems Thinking | Digital Research
name: Nicolas Arias Garcia
description: "Portfolio site showcasing research in anthropology with technical applications"
url: https://9scorp4.github.io
repository: "9scorp4/9scorp4.github.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "anthroposai"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name: "Nicolas Arias Garcia"
  avatar: "/assets/images/profile.jpg" # Add a profile image later
  bio: "Researcher with a background in anthropology, specializing in the integration of numerical methods in social science research."
  location: "Montreal, Quebec"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/9scorp4"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/nicag/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/9scorp4"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/nicag/"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true
      related: true
      sidebar:
        nav: "projects"

# Include
include:
  - _pages