# Site settings
title: Nicolas Arias Garcia
subtitle: Anthropology | Systems Thinking | Digital Research
name: Nicolas Arias Garcia
description: "Portfolio showcasing research in anthropology with technical applications"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Remote theme
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "anthroposai"

# Plugins (must be in this order)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Conversion settings
incremental: false

# Handling Reading
safe: true
source: .
destination: ./_site

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Markdown Processing
rdiscount:
  extensions: []

# Sass Configuration
sass:
  style: compressed
  sourcemap: never
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/css